import test from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {validReview,createReviewsApi} from '../backend/node/reviews-api.mjs';
test('reviews enforce integer ratings, length and text types',()=>{assert.equal(validReview({rating:5,comment:'Buena experiencia con Rumbo'}),true);for(const rating of [0,6,2.5,'5',null])assert.equal(validReview({rating,comment:'Comentario válido'}),false);for(const comment of ['',{},'a'.repeat(1201),'hola\u0000mundo'])assert.equal(validReview({rating:3,comment}),false);});
function fixture({user={Id:'id',FullName:'Ana Pérez'},enabled=true}={}){const calls=[];const pool={request(){const args={};return {input(k,t,v){args[k]=v;return this;},async query(q){calls.push({q,args});return {recordsets:[[{total:0,average:null}],[]]};}};}};return {calls,handler:createReviewsApi({enabled:()=>enabled,getDatabase:async()=>({pool,sql:{Int:'int',VarChar:()=>'',NVarChar:()=>'',MAX:1}}),userSession:async()=>user})};}
async function invoke(handler,{method='GET',body,origin='http://localhost',url='/api/reviews'}={}){const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);Object.assign(req,{url,method,headers:{host:'localhost',origin,'content-type':'application/json'}});const res={writeHead(status){this.status=status;},end(data){this.data=JSON.parse(data);}};await handler(req,res);return res;}
test('public reviews return real empty aggregate and paginate',async()=>{const f=fixture();const r=await invoke(f.handler,{url:'/api/reviews?page=2'});assert.equal(r.status,200);assert.equal(r.data.total,0);assert.equal(r.data.average,null);assert.equal(f.calls[0].args.offset,12);});
test('review posting requires account and same origin',async()=>{for(const [user,origin,status]of [[null,'http://localhost',401],[{},'https://evil.example',403]]){const f=fixture({user});const r=await invoke(f.handler,{method:'POST',origin,body:{rating:5,comment:'Mi reseña de prueba'}});assert.equal(r.status,status);assert.equal(f.calls.length,0);}});
test('review uses authenticated first name, parameterized payload and one account key',async()=>{const f=fixture();const r=await invoke(f.handler,{method:'POST',body:{rating:2,comment:'<script>alert(1)</script>',name:'Impostor'}});assert.equal(r.status,200);const c=f.calls[0];assert.equal(c.args.key,'review:id');assert.equal(JSON.parse(c.args.data).name,'Ana');assert.ok(!c.q.includes('<script>'));assert.match(c.q,/UPDLOCK,HOLDLOCK/);assert.match(c.q,/UPDATE dbo.RumboSettings/);});
test('unavailable database never pretends a review was saved',async()=>{const f=fixture({enabled:false});const r=await invoke(f.handler,{method:'POST'});assert.equal(r.status,503);});
test('deleting rejects guests and foreign origins without touching reviews',async()=>{for(const [user,origin,status]of [[null,'http://localhost',401],[{Id:'owner'},'https://evil.example',403]]){const f=fixture({user});const r=await invoke(f.handler,{method:'DELETE',origin});assert.equal(r.status,status);assert.equal(f.calls.length,0);}});
test('deleting ignores forged owner IDs in both body and query',async()=>{const f=fixture({user:{Id:'owner'}});const r=await invoke(f.handler,{method:'DELETE',url:'/api/reviews?id=victim&owner=victim',body:{id:'victim',key:'review:victim'}});assert.equal(r.status,200);assert.equal(r.data.deleted,true);assert.equal(f.calls.length,1);assert.equal(f.calls[0].args.key,'review:owner');assert.match(f.calls[0].q,/DELETE.*WHERE Name=@key/);});
