import test from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {validReview,createReviewsApi} from '../backend/node/reviews-api.mjs';
test('reviews enforce integer ratings, length and text types',()=>{assert.equal(validReview({rating:5,comment:'Buena experiencia con Rumbo'}),true);for(const rating of [0,6,2.5,'5',null])assert.equal(validReview({rating,comment:'Comentario válido'}),false);for(const comment of ['',{},'a'.repeat(1201),'hola\u0000mundo'])assert.equal(validReview({rating:3,comment}),false);});
function fixture({user={Id:'id',FullName:'Ana Pérez'},enabled=true,result={recordsets:[[{total:0,average:null}],[]],recordset:[{Name:'review:id'}]}}={}){const calls=[];const pool={request(){const args={};return {input(k,t,v){args[k]=v;return this;},async query(q){calls.push({q,args});return result;}};}};return {calls,handler:createReviewsApi({enabled:()=>enabled,getDatabase:async()=>({pool,sql:{Int:'int',VarChar:()=>'',NVarChar:()=>'',MAX:1}}),userSession:async()=>user})};}
async function invoke(handler,{method='GET',body,origin='http://localhost',url='/api/reviews'}={}){const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);Object.assign(req,{url,method,headers:{host:'localhost',origin,'content-type':'application/json'}});const res={writeHead(status){this.status=status;},end(data){this.data=JSON.parse(data);}};await handler(req,res);return res;}
test('public reviews return real empty aggregate and paginate',async()=>{const f=fixture();const r=await invoke(f.handler,{url:'/api/reviews?page=2'});assert.equal(r.status,200);assert.equal(r.data.total,0);assert.equal(r.data.average,null);assert.equal(f.calls[0].args.offset,12);});
test('review posting requires account and same origin',async()=>{for(const [user,origin,status]of [[null,'http://localhost',401],[{},'https://evil.example',403]]){const f=fixture({user});const r=await invoke(f.handler,{method:'POST',origin,body:{rating:5,comment:'Mi reseña de prueba'}});assert.equal(r.status,status);assert.equal(f.calls.length,0);}});
test('each publication gets a separate ID and uses the authenticated name',async()=>{const f=fixture();for(let i=0;i<2;i++){const r=await invoke(f.handler,{method:'POST',body:{rating:2,comment:'<script>alert(1)</script>',name:'Impostor'}});assert.equal(r.status,200);const c=f.calls[i];assert.match(c.args.key,/^review:id:[a-f0-9-]{36}$/);assert.equal(r.data.id,c.args.key);assert.equal(JSON.parse(c.args.data).name,'Ana');assert.ok(!c.q.includes('<script>'));assert.match(c.q,/INSERT/);assert.doesNotMatch(c.q,/UPDATE/);}assert.notEqual(f.calls[0].args.key,f.calls[1].args.key);});
test('unavailable database never pretends a review was saved',async()=>{const f=fixture({enabled:false});const r=await invoke(f.handler,{method:'POST'});assert.equal(r.status,503);});
test('deleting rejects guests and foreign origins without touching reviews',async()=>{for(const [user,origin,status]of [[null,'http://localhost',401],[{Id:'owner'},'https://evil.example',403]]){const f=fixture({user});const r=await invoke(f.handler,{method:'DELETE',origin});assert.equal(r.status,status);assert.equal(f.calls.length,0);}});
test('deleting scopes the selected ID to the authenticated owner, ignoring forged ownership',async()=>{const f=fixture({user:{Id:'owner'}});const r=await invoke(f.handler,{method:'DELETE',url:'/api/reviews?id=review:owner:abc&owner=victim',body:{id:'victim',key:'review:victim'}});assert.equal(r.status,200);assert.equal(r.data.deleted,true);assert.equal(f.calls.length,1);assert.equal(f.calls[0].args.key,'review:owner:abc');assert.equal(f.calls[0].args.ownKey,'review:owner');assert.match(f.calls[0].q,/WHERE Name=@key AND \(Name=@ownKey OR Name LIKE @ownKey\+':%'\)/);});
test('deleting without a valid selection never deletes all account reviews',async()=>{for(const id of ['', '?id=', '?id=victim', '?id=review:abc%25', '?id=review:'+ 'x'.repeat(80)]){const f=fixture();assert.equal((await invoke(f.handler,{method:'DELETE',url:'/api/reviews'+id})).status,400);assert.equal(f.calls.length,0);}});
test('foreign, missing or already deleted review returns 404',async()=>{const f=fixture({result:{recordset:[]}});const r=await invoke(f.handler,{method:'DELETE',url:'/api/reviews?id=review:victim'});assert.equal(r.status,404);assert.notEqual(r.data.deleted,true);});
test('legacy review IDs can still be selected individually',async()=>{const f=fixture();assert.equal((await invoke(f.handler,{method:'DELETE',url:'/api/reviews?id=review:id'})).status,200);assert.equal(f.calls[0].args.key,'review:id');});
test('listing includes IDs and boolean ownership per card',async()=>{const f=fixture({result:{recordsets:[[{total:2,average:4,hasOwnReview:1}],[{id:'review:id',isOwn:1},{id:'review:other:abc',isOwn:0}]]}});const r=await invoke(f.handler);assert.equal(r.data.hasOwnReview,true);assert.deepEqual(r.data.reviews,[{id:'review:id',isOwn:true},{id:'review:other:abc',isOwn:false}]);});
