import fs from 'node:fs/promises';
import vm from 'node:vm';
const read=p=>fs.readFile(p,'utf8');
const write=(p,s)=>fs.writeFile(p,s.trimEnd()+'\n');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let home=await read('index.html');
home=home.replace(/<a class="campaign-credits"[^>]*>[\s\S]*?<\/a>/g,'').replace('<a href="viajes.html?pantalla=destinos#creditos-imagenes">Créditos de fotografías</a>','<a href="servicios.html?seccion=legal">Información legal</a>');
await write('index.html',home);
let viajes=await read('viajes.html');
const block=viajes.match(/<details id="creditos-imagenes"[\s\S]*?<\/details>/)?.[0];
if(!block)throw new Error('No se encontró el bloque original de atribuciones');
viajes=viajes.replace(block,'').replace('href="viajes.html?pantalla=destinos#creditos-imagenes">Créditos de imágenes','href="servicios.html?seccion=legal">Información legal');
await write('viajes.html',viajes);
let travel=await read('viajes.js');
travel=travel.split('\n').filter(line=>!line.includes('<details class="rv-photo-credit">')).join('\n');
await write('viajes.js',travel);
const hotels=JSON.parse(await read('imagenes-viajes/CREDITOS-HOTELES.json'));
let store=await read('tienda.js');
const creditStart=store.indexOf('const PHOTO_CREDITS = ')+21;
const storeCredits=vm.runInNewContext('('+store.slice(creditStart,store.indexOf('];',creditStart)+1)+')');
const line=(title,source,author,license,licenseUrl)=>`<li><a href="${esc(source)}">${esc(title)}</a> · ${esc(author.replace(/<[^>]*>/g,''))} · <a href="${esc(licenseUrl||source)}">${esc(license)}</a></li>`;
const hotelItems=hotels.map(h=>line(h.hotel+' · '+h.destination,h.source,h.author,h.license,h.licenseUrl)).join('');
const storeItems=storeCredits.map(h=>line(h.title,h.page,h.author,h.license,h.licenseUrl)).join('');
const legal=`<template id="legal-content"><section class="help-card legal-attributions"><h2>Fotografías y licencias</h2><p>Las fotografías se presentan con encuadres adaptados. Los hospedajes y tarifas del catálogo son de demostración; sus fotografías son referencias visuales.</p>${block.replace(/<details[^>]*>|<\/details>|<summary>[\s\S]*?<\/summary>/g,'')}<h3>Hospedajes</h3><ul>${hotelItems}</ul><h3>Tienda</h3><ul>${storeItems}</ul></section></template>`;
let services=await read('servicios.html');
services=services.replace('</body>',legal+'\n</body>').replace('<a href="servicios.html?seccion=privacidad">Privacidad</a>','<a href="servicios.html?seccion=privacidad">Privacidad</a><a href="servicios.html?seccion=legal">Información legal</a>');
await write('servicios.html',services);
let serviceCode=await read('servicios.js');
serviceCode=serviceCode.replaceAll('href="index.html#servicios"','href="servicios.html"');
serviceCode=serviceCode.replace("  else if(Object.hasOwn(help,section))helpPage(section);",`  else if(section==='equipo')location.replace('index.html#nuestro-equipo');
  else if(section==='legal'){document.title='Información legal | Rumbo';root.innerHTML=crumb('Información legal')+hero('Información legal.','Fuentes y licencias de los recursos visuales de Rumbo.','RUMBO')+document.querySelector('#legal-content').innerHTML;}
  else if(Object.hasOwn(help,section))helpPage(section);`);
await write('servicios.js',serviceCode);
let storeHtml=await read('tienda.html');
storeHtml=storeHtml.replace(/<details class="photo-credits">[\s\S]*?<\/details>/,'<a href="servicios.html?seccion=legal">Información legal</a>');
await write('tienda.html',storeHtml);
const start=store.indexOf('  PHOTO_CREDITS.filter('),end=store.indexOf('  // ==========================================================\n  // AÑO',start);
// CRLF y LF se normalizan antes de localizar el final del bloque.
store=store.replace(/  PHOTO_CREDITS\.filter\([\s\S]*?(?=  \/\/ =+\r?\n  \/\/ AÑO)/,'');
await write('tienda.js',store);
